apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app:  nginx
    demo: service
spec:
  # list of containers
  containers:
  - name: nginx-nodeport
    image: nginx
    ports:
    - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: nodeport
  selector:
    app:  nginx-nodeport
    demo: service
  ports:
    - protocol: TCP
      port: 80 #service-port
      targetPort: 9376 # container-port

