apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: DevOps
    Trainee: "KBhanuTejaNamana"
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort:  80